sudo: false

language: c

python:
  - "3.4"

addons:
  apt:
    packages:
      - cmake
      - libevent-dev
      - libglib2.0-dev
      - libgmime-2.6-dev
      - libluajit-5.1-dev
      - libmagic-dev
      - libpcre3-dev
      - libssl-dev
      - make
      - ragel
      - redis-server

script:
  - cmake . -DCMAKE_INSTALL_PREFIX=./_install -DCMAKE_C_COMPILER=$CC
  - cmake --build . --target install
  - sudo pip install robotframework
  - sudo robot test/functional/cases

compiler:
  - clang
  - gcc

branches:
  only:
    - master
